version: "3.4"
services:
     postgres:
          image: postgres
          environment:
               POSTGRES_DB: ${DB_NAME}
               POSTGRES_USER: ${DB_USER}
               POSTGRES_PASSWORD: ${DB_PASS}
          ports:
               - "${DB_PORT}:${DB_PORT}"
     web:
          build: .
          command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
          volumes: 
               - .:/code
          ports:
               - "8000:8000"
          depends_on:
               - postgres
          restart: on-failure